set_property PACKAGE_PIN A6 [get_ports csi_iic_scl_io]
set_property PACKAGE_PIN A8 [get_ports csi_iic_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports csi_iic_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports csi_iic_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN B1 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN B2 [get_ports {GPIO_0_0_tri_io[2]}]

set_property PACKAGE_PIN A9 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN B7 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN A3 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN A4 [get_ports {GPIO_0_0_tri_io[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports ext_iic_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports ext_iic_sda_io]
set_property PACKAGE_PIN A7 [get_ports ext_iic_scl_io]
set_property PACKAGE_PIN B9 [get_ports ext_iic_sda_io]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[5]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[4]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[3]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[2]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[1]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[0]}]

set_property PULLUP true [get_ports csi_iic_scl_io]
set_property PULLUP true [get_ports csi_iic_sda_io]
set_property PULLUP true [get_ports ext_iic_scl_io]
set_property PULLUP true [get_ports ext_iic_sda_io]
