# La socket di seatd deve essere accessibile all'utente della sessione
# Weston (ked): il gruppo di default della unit Buildroot non lo consente.
[Service]
ExecStart=
ExecStart=/usr/bin/seatd -g video
